server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 50
 
logging:
  config: classpath:log4j2.xml
   
jasypt:
  encryptor:
    password: salt

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

management:
  endpoints:
    web:
      exposure: 
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql.mysqldb:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: ENC(BkWK9huHhX3U0LJFDttiFA==)
    
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      minimum-idle: 1
      maximum-pool-size: 5