apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: springio-demo
  name: springio-demo
  namespace: springio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springio-demo
  template:
    metadata:
      labels:
        app: springio-demo
    spec:
      containers:
      - image: elittlewhite/springio-demo:1.0.1
        name: springio-demo
        ports:
            - containerPort: 8080
        imagePullPolicy: Always
        #https://kubernetes.io/docs/concepts/containers/images/#updating-images